require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlatePhotosController do

  # This should return the minimal set of attributes required to create a valid
  # PlatePhoto. As you add validations to PlatePhoto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "image" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlatePhotosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all plate_photos as @plate_photos" do
      plate_photo = PlatePhoto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:plate_photos).should eq([plate_photo])
    end
  end

  describe "GET show" do
    it "assigns the requested plate_photo as @plate_photo" do
      plate_photo = PlatePhoto.create! valid_attributes
      get :show, {:id => plate_photo.to_param}, valid_session
      assigns(:plate_photo).should eq(plate_photo)
    end
  end

  describe "GET new" do
    it "assigns a new plate_photo as @plate_photo" do
      get :new, {}, valid_session
      assigns(:plate_photo).should be_a_new(PlatePhoto)
    end
  end

  describe "GET edit" do
    it "assigns the requested plate_photo as @plate_photo" do
      plate_photo = PlatePhoto.create! valid_attributes
      get :edit, {:id => plate_photo.to_param}, valid_session
      assigns(:plate_photo).should eq(plate_photo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlatePhoto" do
        expect {
          post :create, {:plate_photo => valid_attributes}, valid_session
        }.to change(PlatePhoto, :count).by(1)
      end

      it "assigns a newly created plate_photo as @plate_photo" do
        post :create, {:plate_photo => valid_attributes}, valid_session
        assigns(:plate_photo).should be_a(PlatePhoto)
        assigns(:plate_photo).should be_persisted
      end

      it "redirects to the created plate_photo" do
        post :create, {:plate_photo => valid_attributes}, valid_session
        response.should redirect_to(PlatePhoto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved plate_photo as @plate_photo" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlatePhoto.any_instance.stub(:save).and_return(false)
        post :create, {:plate_photo => { "image" => "invalid value" }}, valid_session
        assigns(:plate_photo).should be_a_new(PlatePhoto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlatePhoto.any_instance.stub(:save).and_return(false)
        post :create, {:plate_photo => { "image" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested plate_photo" do
        plate_photo = PlatePhoto.create! valid_attributes
        # Assuming there are no other plate_photos in the database, this
        # specifies that the PlatePhoto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlatePhoto.any_instance.should_receive(:update_attributes).with({ "image" => "MyString" })
        put :update, {:id => plate_photo.to_param, :plate_photo => { "image" => "MyString" }}, valid_session
      end

      it "assigns the requested plate_photo as @plate_photo" do
        plate_photo = PlatePhoto.create! valid_attributes
        put :update, {:id => plate_photo.to_param, :plate_photo => valid_attributes}, valid_session
        assigns(:plate_photo).should eq(plate_photo)
      end

      it "redirects to the plate_photo" do
        plate_photo = PlatePhoto.create! valid_attributes
        put :update, {:id => plate_photo.to_param, :plate_photo => valid_attributes}, valid_session
        response.should redirect_to(plate_photo)
      end
    end

    describe "with invalid params" do
      it "assigns the plate_photo as @plate_photo" do
        plate_photo = PlatePhoto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlatePhoto.any_instance.stub(:save).and_return(false)
        put :update, {:id => plate_photo.to_param, :plate_photo => { "image" => "invalid value" }}, valid_session
        assigns(:plate_photo).should eq(plate_photo)
      end

      it "re-renders the 'edit' template" do
        plate_photo = PlatePhoto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlatePhoto.any_instance.stub(:save).and_return(false)
        put :update, {:id => plate_photo.to_param, :plate_photo => { "image" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested plate_photo" do
      plate_photo = PlatePhoto.create! valid_attributes
      expect {
        delete :destroy, {:id => plate_photo.to_param}, valid_session
      }.to change(PlatePhoto, :count).by(-1)
    end

    it "redirects to the plate_photos list" do
      plate_photo = PlatePhoto.create! valid_attributes
      delete :destroy, {:id => plate_photo.to_param}, valid_session
      response.should redirect_to(plate_photos_url)
    end
  end

end
